### ISSUE TITLE
Umbrella: Event Management

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#122]
Provide an ability to manage events via admin interface. 

This depends on #91 
And on Authentication and User Accounts (admin only for now)

### Before Calendar is Published
Event management should be split into two roles: Promoters and NCNCA Members.

* Promoters should be able to create events and  they will be shown in a Draft of the calendar. 
* Each event should be approved by NCNCA Member
* When all events are approved—calendar is ready to be published
* If promoter makes any changes—event should be approved again

### After calendar is published
* promoters should be able to move/cancel events (with automatic notifications of all racers and NCNCA)
* promoters should be able to edit non-crucial information for their event, like replace a flyer, add registration notes and description, fix start times or categories

--

We need to target NCNCA requirements first, most important ones include:
* [ ] uploading flyiers
* [ ] map of the start
* [ ] pre-defined list of promoters and event series
* [ ] other event properties from #91 
* [ ] ability to Cancel and Move events (Promoters, NCNCA) 
* [ ] ability to approve events
* [ ] ability to approve calendar

**Comment by Restuta** [comment]
For file uploading we may use Amazon:

http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-examples.html#Uploading_a_local_file_using_the_File_API

**Comment by Restuta** [comment]
For maps we can consider https://github.com/Leaflet/Leaflet

**Comment by Restuta** [comment]
for address autocomplete https://www.producthunt.com/tech/algolia-places
