### ISSUE TITLE
Umbrella: Main events page with fake data

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#3]
Depends on:
- [x] #10 Client-side infrastructure
- [x] #6 Sketch + draft 
- [x] #13 Implement Sketched UI
- [x] #4 Define event structure in JSON
- [x] #5 Generate fake data
- [x] #7 Pick colors and fonts
- [x] #8 Pick UI stack
- [x] #9 Create card UI
