### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by Restuta** [Restuta/rcn.io#40]
This is an umbrella feature for a new use onboarding process (registering a first-timer user). A good learning material can be found here: https://www.useronboard.com

#### Requirements
* [ ] collect USAC licence #
   * [ ] pull name from USAC by lic # ([example url](https://www.usacycling.org/results/index.php?compid=458433))
* [ ] collect email
   * [ ] load avatar from gravatar if available
* [ ] (optionally) "Sign Up with Facebook" (gives us Email and Name, we can double-check name from USAC)

**Comment by Restuta** [comment]
![](http://media3.giphy.com/media/OrhLAi1t2qveM/giphy.gif)

**Comment by Me4ta** [comment]
I think we need password to protect their personal data. Especially if we are going to ask them to share their own family events with us.

**Comment by Restuta** [comment]
@Me4ta their data protected, what do you mean?
